<a href="https://colab.research.google.com/github/MiguelCigano/python_telecom/blob/main/numpy_.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Numpy para gente con prisa

####Configuración previa

El análisis de datos básico se realiza en Python con tres paquetes básicos, que se complementan entre ellas:

- **Numpy**: para operaciones de **algebra líneal**.
- **Pandas**: para manejo de **dataframes**.
- **Matplotlib**: para vizualización de **gŕaficos**.

Son paquetes externos a Python, por lo que tenemos que instalarlas para poder usarlas.



```
<pip install numpy>
```


Si usas conda como administrador de ambientes, puedes usar:


```
<conda install -c anaconda numpy>
```



https://numpy.org/

Considera hecharle un ojo a el uso de Markdown en Collab:
https://colab.research.google.com/notebooks/markdown_guide.ipynb


Tambien se puede instalar desde el Collab usando:

```
<!pip install numpy>
```



In [1]:
import numpy as np

La programación gráfica se basa en la idea de manipular información almacenada estructuras conocidos como  **vectores**  y **matrices**.

En Python, aunque existen las listas, no es coveniente usarlas como si fueran vectores debido a que solo son colecciones y están limitadas en operaciones matemáticas.

Sin embargo, **Numpy** viene a solucionar esa limitación ofreciendo los arreglos, (**array**), los cuales son un tipo de datos parecido a las listas.

In [4]:
arreglo = np.array([1, 2, 4, 8, 6])
arreglo

array([1, 2, 4, 8, 6])

In [5]:
print(arreglo)

[1 2 4 8 6]


In [6]:
type(arreglo)

numpy.ndarray

Se puede consultar la dimensión y la forma de un dato tipo **array** (arreglo) usando las propiedades `ndim` y `shape`.





In [8]:
arreglo_2 = np.array([1, 2, 3, "Hola", 3.1416])
type(arreglo_2)

numpy.ndarray

In [10]:
arreglo_2.ndim

1

In [12]:
arreglo_2.shape

(5,)

Podemos definir un tipo de dato **array** a partir de una lista anidada, es decir, un arreglo formado por dos sublistas.

In [22]:
arreglo_3 = np.array(
    [
        [1, 2, 3, 4, 5],
        [10, 20, 30, 40, 50]
    ]
)

In [23]:
print(arreglo_3)

[[ 1  2  3  4  5]
 [10 20 30 40 50]]


In [20]:
arreglo_3.ndim

2

In [19]:
arreglo_3.shape

(2, 5)

In [24]:
arreglo.dtype

dtype('int64')

In [25]:
arreglo_4 = np.array([1, 2, 3.1416])
arreglo_4.dtype

dtype('float64')

In [26]:
arreglo_5 = np.array(["Hola", "Telecomunicaciones", "Mundo"])
arreglo_5.dtype

dtype('<U18')

In [31]:
arreglo_6 = np.array(["Hola", 3, 4, 5])
arreglo_6.dtype

dtype('<U21')